- name: Create tweet content
  id: tweet-content
  if: steps.post-info.outputs.title != ''
  run: |
    TITLE="${{ steps.post-info.outputs.title }}"
    CATEGORY="${{ steps.post-info.outputs.category }}"
    DATE="${{ steps.post-info.outputs.date }}"
    FILENAME="${{ steps.post-info.outputs.filename }}"

    POST_URL="https://naoqoo2.github.io/blog/${DATE//\-/\/}/${FILENAME%.md}/"

    if [ "$CATEGORY" = "cooking" ]; then
      TWEET_TEXT=$(cat <<'EOF'
新しい料理レシピを投稿しました！
__TITLE__
__URL__
#料理 #レシピ #ブログ #育休メシ
EOF
)
    elif [ "$CATEGORY" = "retrospective" ]; then
      TWEET_TEXT=$(cat <<'EOF'
振り返り記事を投稿しました！
__TITLE__
__URL__
#振り返り #ふりかえり #ブログ #エンジニア
EOF
)
    else
      TWEET_TEXT=$(cat <<'EOF'
新しい記事を投稿しました！
__TITLE__
__URL__
#ブログ #技術 #エンジニア
EOF
)
    fi

    TWEET_TEXT="${TWEET_TEXT/__TITLE__/$TITLE}"
    TWEET_TEXT="${TWEET_TEXT/__URL__/$POST_URL}"

    ENCODED_TWEET=$(echo "$TWEET_TEXT" | python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read()))")
    echo "content=$ENCODED_TWEET" >> "$GITHUB_OUTPUT"
