name: Build Marp Slides

on:
  push:
    branches: [ main ]
    paths:
      - '_posts/**/*.md'
  pull_request:
    branches: [ main ]
    paths:
      - '_posts/**/*.md'

jobs:
  marp-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Find Marp files
        id: find-marp
        run: |
          # layout: marp を含むファイルを検索
          marp_files=$(find _posts -name "*.md" -exec grep -l "layout: marp" {} \;)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$marp_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Convert Marp to HTML
        if: steps.find-marp.outputs.files != ''
        run: |
          # assets/slides ディレクトリを作成
          mkdir -p assets/slides
          
          # 各Marpファイルを処理
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              echo "Converting: $file"
              # ファイル名から日付プレフィックスを取得
              basename_file=$(basename "$file" .md)
              
              # HTMLファイル名を生成（日付プレフィックスは保持）
              html_file="assets/slides/${basename_file}.html"
              
              # Marp CLIで変換（カスタムCSSとテーマを適用）
              marp "$file" \
                --output "$html_file" \
                --html \
                --theme-set ./assets/css/marp-theme.css \
                --theme default || echo "Warning: Failed to convert $file"
                
              echo "Generated: $html_file"
            fi
          done <<< "${{ steps.find-marp.outputs.files }}"

      - name: Commit generated files
        if: steps.find-marp.outputs.files != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 生成されたファイルをステージング
          git add assets/slides/*.html
          
          # 変更があればコミット
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generated Marp slides [skip ci]"
            git push
          fi